# Generated by Django 3.0 on 2019-12-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_moderation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_publish',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Опубликован: '),
        ),
    ]
